config/routes.rb
VitalCoaches::Application.routes.draw do
  get "page/index"

  namespace :members do
    root :to => "pages#index"

    resources :workouts
    
    
    resource :diary
    resources :diary_entries
    resource :profile
    resource :videos do
      resource "nutrition", :only => [:show] do
        get 'lectures/:lecture_id' => 'nutritions#lecture', :as => :lecture
      end
      get "fitness"
      get "motivation"
    end
    resources :pictures
    resources :recipes
    resource :user
  end

  match "ueber_uns" => "page#about", :as => :about
  match "coaches" => "page#coaches", :as => :coaches
  match "agb" => "page#terms", :as => :terms
  match "impressum" => "page#imprint", :as => :imprint

  match "ernaehrungstagebuch" => "page#diary", :as => :diary

  devise_for :users
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
    get "sign_out", :to => "devise/sessions#destroy"
  end

  root :to => 'page#index'

end

app/controllers/members/application_controller.rb
# -*- encoding : utf-8 -*-
class Members::ApplicationController < ApplicationController  
  #layout "internal"
  before_filter :authenticate_user!

  before_filter :check_profile_created

  before_filter :do_breadcrumbs

  helper_method :breadcrumbs

  def breadcrumbs
    @crumbs
  end

  def add_crumb name, url
    @crumbs.push [name, url]    
  end

  private

  def do_breadcrumbs
    @crumbs = []
    @crumbs.push ["Start", members_root_path]    
  end

  def check_profile_created
  	unless request.fullpath == new_members_profile_path
  	  redirect_to new_members_profile_path if current_user.profile.nil?
  	end  	
  end
end

app/controllers/members/diaries_controller.rb
# -*- encoding : utf-8 -*-
class Members::DiariesController < Members::ApplicationController  
  
  def show
    add_crumb "Tagebuch", members_diary_path
    @diary_entries = current_user.diary_entries

    @json_events = []
    @diary_entries.each do |diary_entry|
      @json_events << {:title => "G: #{diary_entry.weight}", :start => diary_entry.entry_date}
    end    

    @json_events = @json_events.to_json
  end

end

app/controllers/members/diary_entries_controller.rb
# -*- encoding : utf-8 -*-
class Members::DiaryEntriesController < Members::ApplicationController  
  
  def create
    diary_entry = DiaryEntry.new params[:diary_entry]
    diary_entry.user = current_user

    if diary_entry.save
      redirect_to members_diary_path
    else
      flash[:warning] = "Fehler beim speichern!"
      redirect_to members_diary_path
    end
  end

end

app/controllers/members/nutritions_controller.rb
# -*- encoding : utf-8 -*-
class Members::NutritionsController < Members::ApplicationController

  before_filter :set_values
  before_filter :set_breadcrumb

  def show    
  end

  def lecture
    add_crumb "Ernährungsvideos", members_videos_nutrition_path

    #render "lektion#{params[:lecture_id]}"
    @lecture = get_lecture params[:lecture_id]
    #@lecture = params[:lecture_id]
    render "lecture"
  end

  private

  def get_lecture id    
    result = nil
    @lecutures.each do |lecture|
      result = lecture if lecture[:id] == id.to_i
    end
    result
  end

  def set_breadcrumb
    add_crumb "Videos", members_videos_nutrition_path
    
  end

  def set_values
    @lecutures = [
      {:id => 1, :name => "JoJo-Effekt", :description => "JoJo-Effekt verhindern; warum Diäten nicht funktionieren", :video_description => 
        "In der ersten Video-Lektion führen wir Dich in die Grundlagen ein. Nachdem Du das Video zu Ende gesehen hast beginnt das Quiz. Dort wird mit einfachen Fragen abgeprüft, ob Du auch gut zugesehen hast :)", 
        :video_id => "5OVT2bVwIBE"
      },
      {:id => 2, :name => "Blutzucker", :description => "Blutzucker", :video_description => "in der zweiten Lektion erfährst Du, was Hunger auslöst und wie wir das Wissen für unsere Ernährung nutzen können.", 
        :video_id => "GtPOhwY94_w"
        },
      {:id => 3, :name => "Gewicht", :description => "Übergewicht erkennen"},
      {:id => 4, :name => "Zählen", :description => "Kalorienzählen: sinnvoll oder nicht?"},
      {:id => 5, :name => "Alltag", :description => "Ernährungsgewohnheiten ändern"},
      {:id => 6, :name => "Frühstück", :description => "Frühstück"},
      {:id => 7, :name => "Mittags", :description => "Mittagessen"},
      {:id => 8, :name => "Abends", :description => "Abendessen"},
      {:id => 9, :name => "K.hydrate", :description => "Kohlenhydrate"},
      {:id => 10, :name => "Eiweis", :description => "Eiweis"},
      {:id => 11, :name => "Fette", :description => "Fette"},
      {:id => 12, :name => "Vitamine", :description => "Vitamine"},
      {:id => 13, :name => "Getränke", :description => "Getränke"},
      {:id => 14, :name => "Sport", :description => "Sport"},
      {:id => 15, :name => "Fazit", :description => "Fazit aus Staffel 1"}
      ]
  end
end

app/controllers/members/pages_controller.rb
# -*- encoding : utf-8 -*-
class Members::PagesController < Members::ApplicationController
  def index
    current_user.reset_authentication_token!
  end
end

app/controllers/members/pictures_controller.rb
# -*- encoding : utf-8 -*-
class Members::PicturesController < Members::ApplicationController
end

app/controllers/members/profiles_controller.rb
# -*- encoding : utf-8 -*-
class Members::ProfilesController < Members::ApplicationController
	# even a singular resource like account needs a pluralized controller, see http://guides.rubyonrails.org/routing.html#singular-resources

  def show
    @profile = current_user.profile
    @user = current_user
  end

  def new
    current_user.reset_authentication_token!
    @user = current_user
    if @user.profile.nil?
      @user.profile = Profile.new
    end
  end

  def create
    @user = current_user    
    if @user.profile.update_attributes(params[:profile])
      render js: "window.location.pathname='#{members_profile_path}'"
    else
      render js: "alert('Daten Fehlerhaft');"
    end    
  end  
  
end

app/controllers/members/recipes_controller.rb
# -*- encoding : utf-8 -*-
class Members::RecipesController < Members::ApplicationController
end

app/controllers/members/users_controller.rb
# -*- encoding : utf-8 -*-
class Members::UsersController < Members::ApplicationController
	# even a singular resource like account needs a pluralized controller, see http://guides.rubyonrails.org/routing.html#singular-resources  

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to members_profile_path
    else
      # add a error message
      redirect_to members_profile_path
    end
  end
  
end

app/controllers/members/videos_controller.rb
# -*- encoding : utf-8 -*-
class Members::VideosController < Members::ApplicationController
end

app/controllers/members/workouts_controller.rb
# -*- encoding : utf-8 -*-
class Members::WorkoutsController < Members::ApplicationController

  def index
    @workouts = current_user.workouts    
  end

  def create
    workout = Workout.new params[:workout]
    workout.user = current_user

    if workout.save
      redirect_to members_workouts_path
    else
      flash[:warning] = "Fehler beim speichern!"
      redirect_to members_workouts_path
    end
  end
end

app/controllers/members_controller.rb
# -*- encoding : utf-8 -*-
class MembersController < ApplicationController
  layout "internal"
  def index
  end  
end

app/helpers/members/application_helper.rb
# -*- encoding : utf-8 -*-
module Members::ApplicationHelper

  def nav_list_elmement name, url, icon_name
    capture_haml do
      if current_page? url
        haml_tag(:li, :class => :active) do
          haml_tag :a, :href => url do
            haml_tag :i, :class => icon_name
            haml_tag "span.menu-text", name
          end
        end
      else
        haml_tag(:li) do
          haml_tag :a, :href => url do
            haml_tag :i, :class => icon_name
            haml_tag "span.menu-text", name
          end
        end
      end      
    end
  end  

end

app/helpers/members/diaries_helper.rb
# -*- encoding : utf-8 -*-
module Members::DiariesHelper
end

app/helpers/members/pages_helper.rb
# -*- encoding : utf-8 -*-
module Members::PagesHelper
end

app/helpers/members/pictures_helper.rb
# -*- encoding : utf-8 -*-
module Members::PicturesHelper
end

app/helpers/members/profiles_helper.rb
# -*- encoding : utf-8 -*-
module Members::ProfilesHelper
end

app/helpers/members/recipes_helper.rb
# -*- encoding : utf-8 -*-
module Members::RecipesHelper
end

app/helpers/members/videos_helper.rb
# -*- encoding : utf-8 -*-
module Members::VideosHelper
end

app/views/members/nutritions/_lecture_button.haml
%p
  = link_to lecture_members_videos_nutrition_path(:lecture_id => lecture_id), :class => "btn btn-app btn-primary radius-10" do
    %i.icon-film
    = lecture_name
    %span.badge.badge-warning
      = lecture_id
  = "Lektion #{lecture_id}: #{lecture_description}"

app/views/members/nutritions/_quiz.haml
%form
  %h3 Quiz
  .quiz
    JoJo-Effekt

    #answer1.draggable
      %p Fett
    #answer2.draggable
      %p Wasser
    #answer3.draggable
      %p Muskelmaße


    #answerbox1.dropable
      %p Antwort 1
    #answerbox2.dropable
      %p Antwort 2
    #answerbox3.dropable
      %p Antwort 3

- content_for :page_specifc_css do
  :css
    .draggable { width: 90px; height: 90px; padding: 0.5em; float: left; margin: 10px 10px 10px 0; }
    .dropable { width: 120px; height: 120px; padding: 0.5em; float: left; margin: 10px; }
- content_for :scripts do
  %script{:src => "http://code.jquery.com/ui/1.10.3/jquery-ui.js"}
- content_for :inline_scripts do
  :javascript
    $(document).ready( function() {
      $(".draggable").draggable({ revert: "invalid" });
      $( "#answerbox1" ).droppable({
        accept: "#answer2",
        activeClass: "ui-state-hover",
        drop: function( event, ui ) {
          $( this )
            .addClass( "ui-state-highlight" )
            .find( "p" )
              .html( "Dropped!" );
        }
      });
    });

app/views/members/nutritions/_quiz_beverages.haml
%form
  %h3 Quiz
  .quiz
    Schätze den Kaloriengehalte der folgenden Getränke:

    %ul.thumbnails
      %li.span5
        .thumbnail
          %h3 1 Flasche Cola
          = image_tag "members/quizes/cola.png"
          %p 
            kcal
            %input.input-small{:type => "text"}
      %li.span5
        .thumbnail
          %h3 1 Flasche Wasser
          = image_tag "members/quizes/wasser.png"
          %p 
            kcal
            %input.input-small{:type => "text"}
    %ul.thumbnails
      %li.span5
        .thumbnail
          %h3 1 Fl. Cola Light
          = image_tag "members/quizes/cola-light.png"
          %p 
            kcal
            %input.input-small{:type => "text"}
      %li.span5
        .thumbnail
          %h3 1 Flasche Saft
          = image_tag "members/quizes/saft.png"
          %p 
            kcal
            %input.input-small{:type => "text"}
    %button.btn.btn-small Abschicken                

app/views/members/nutritions/_video_script.html.erb
<script>
  // 2. This code loads the IFrame Player API code asynchronously.
  var tag = document.createElement('script');

  tag.src = "https://www.youtube.com/iframe_api";
  var firstScriptTag = document.getElementsByTagName('script')[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

  // 3. This function creates an <iframe> (and YouTube player)
  //    after the API code downloads.

  //var player_width = $("#playerframe").css("width");
  var player_width = $(".widget-body").width() - 20;

  var player;
  function onYouTubeIframeAPIReady() {
    player = new YT.Player('player', {
      height: '390',
      width: player_width,
      videoId: '<%= video %>',
      playerVars: { 'controls': 0 , 'modestbranding': 1, 'rel':0, 'showinfo':0, 'theme':'light'},
      events: {
        'onReady': onPlayerReady,
        'onStateChange': onPlayerStateChange
      }
    });
  }

  // 4. The API will call this function when the video player is ready.
  function onPlayerReady(event) {
    //event.target.playVideo();
    $("#start-button").fadeIn();
  }

  // 5. The API calls this function when the player's state changes.
  //    The function indicates that when playing a video (state=1),
  //    the player should play for six seconds and then stop.
  var done = false;
  function onPlayerStateChange(event) {
    if (event.data == YT.PlayerState.ENDED && !done) {
      showQuiz();
    }
  }
  function stopVideo() {
    player.stopVideo();
  }
  function showQuiz() {
      $(".quiz").show();
  };
  $("#start-button").click( function () {
        player.playVideo();        
      });
</script>

app/views/members/nutritions/lecture.haml
.row-fluid
  .span6
    %h1 
      = "Ernährungscoaching: Lektion #{@lecture[:id]}"
    %h2
      = @lecture[:name]
    %p.lead
      = @lecture[:video_description]
    %h3 Los geht's!
.row-fluid
  .span6
    .widget-box
      .widget-header.widget-header-flat
        %h4 Lektion #{@lecture[:id]}
      .widget-body
        .widget-main
          .row-fluid
            .span6#playerframe
              #player
              %button.btn.btn-big{:id => "start-button"} Video starten

          .row-fluid
            .span8
              = render :partial => "quiz"
                    
                    
                

- content_for :scripts do
  %script{:src => "http://vjs.zencdn.net/4.1/video.js" }
- content_for :page_specifc_css do
  %link{:href => "http://vjs.zencdn.net/4.1/video-js.css", :rel => "stylesheet"}/
- content_for :inline_scripts do
  
  :javascript
    $(document).ready( function() {
      / $(".quiz").hide();
      / $("#start-button").hide();
    });
  = render :partial => "video_script", :locals => {:video => @lecture[:video_id]}
  }
    

app/views/members/nutritions/show.haml
%h1 Videolektionen rund ums Thema Ernährung
- @lecutures.each do |lecture|
  = render :partial => "lecture_button", :locals => {:lecture_id => lecture[:id], :lecture_name => lecture[:name], :lecture_description => lecture[:description]}