config/routes.rb
VitalCoaches::Application.routes.draw do
  get "page/index"

  namespace :members do
    root :to => "pages#index"

    resources :workouts
    
    
    resource :diary
    resources :diary_entries
    resource :profile
    resource :videos do
      resource "nutrition", :only => [:show] do
        get 'lectures/:lecture_id' => 'nutritions#lecture', :as => :lecture
      end
      get "fitness"
      get "motivation"
    end
    resources :pictures
    resources :recipes
    resource :user
  end

  match "ueber_uns" => "page#about", :as => :about
  match "coaches" => "page#coaches", :as => :coaches
  match "agb" => "page#terms", :as => :terms
  match "impressum" => "page#imprint", :as => :imprint

  match "ernaehrungstagebuch" => "page#diary", :as => :diary

  devise_for :users
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
    get "sign_out", :to => "devise/sessions#destroy"
  end

  root :to => 'page#index'

end

app/models/profile.rb
# -*- encoding : utf-8 -*-
class Profile < ActiveRecord::Base
  belongs_to :user
  store :anamnesis, accessors: [:already_did_diets, :fruits_frequency, :fastfood_frequency, :snacks_frequency, :cooking,
    :personal_activity, :sports_frequency, :target], coder: JSON
  attr_accessible :abdominal_measurement, :bank_account, :bank_account_owner, 
    :bank_code, :bank_name, :birthday, :body_height, :city, :country, :street, :street_number, :weight, :weight, :zipcode, :already_did_diets, :fruits_frequency, :fastfood_frequency, :snacks_frequency, :cooking,
    :personal_activity, :sports_frequency, :target


    def birthday
    	if read_attribute(:birthday).nil?
    		return Date.today
    	else
    		read_attribute :birthday
    	end
    end
end

app/controllers/members/application_controller.rb
# -*- encoding : utf-8 -*-
class Members::ApplicationController < ApplicationController  
  #layout "internal"
  before_filter :authenticate_user!

  before_filter :check_profile_created

  before_filter :do_breadcrumbs

  helper_method :breadcrumbs

  def breadcrumbs
    @crumbs
  end

  def add_crumb name, url
    @crumbs.push [name, url]    
  end

  private

  def do_breadcrumbs
    @crumbs = []
    @crumbs.push ["Start", members_root_path]    
  end

  def check_profile_created
  	unless request.fullpath == new_members_profile_path
  	  redirect_to new_members_profile_path if current_user.profile.nil?
  	end  	
  end
end

app/controllers/members/diaries_controller.rb
# -*- encoding : utf-8 -*-
class Members::DiariesController < Members::ApplicationController  
  
  def show
    add_crumb "Tagebuch", members_diary_path
    @diary_entries = current_user.diary_entries

    @json_events = []
    @diary_entries.each do |diary_entry|
      @json_events << {:title => "G: #{diary_entry.weight}", :start => diary_entry.entry_date}
    end    

    @json_events = @json_events.to_json
  end

end

app/controllers/members/diary_entries_controller.rb
# -*- encoding : utf-8 -*-
class Members::DiaryEntriesController < Members::ApplicationController  
  
  def create
    diary_entry = DiaryEntry.new params[:diary_entry]
    diary_entry.user = current_user

    if diary_entry.save
      redirect_to members_diary_path
    else
      flash[:warning] = "Fehler beim speichern!"
      redirect_to members_diary_path
    end
  end

end

app/controllers/members/nutritions_controller.rb
# -*- encoding : utf-8 -*-
class Members::NutritionsController < Members::ApplicationController

  before_filter :set_values
  before_filter :set_breadcrumb

  def show    
  end

  def lecture
    add_crumb "Ernährungsvideos", members_videos_nutrition_path

    #render "lektion#{params[:lecture_id]}"
    @lecture = get_lecture params[:lecture_id]
    #@lecture = params[:lecture_id]
    render "lecture"
  end

  private

  def get_lecture id    
    result = nil
    @lecutures.each do |lecture|
      result = lecture if lecture[:id] == id.to_i
    end
    result
  end

  def set_breadcrumb
    add_crumb "Videos", members_videos_nutrition_path
    
  end

  def set_values
    @lecutures = [
      {:id => 1, :name => "JoJo-Effekt", :description => "JoJo-Effekt verhindern; warum Diäten nicht funktionieren", :video_description => 
        "In der ersten Video-Lektion führen wir Dich in die Grundlagen ein. Nachdem Du das Video zu Ende gesehen hast beginnt das Quiz. Dort wird mit einfachen Fragen abgeprüft, ob Du auch gut zugesehen hast :)", 
        :video_id => "5OVT2bVwIBE"
      },
      {:id => 2, :name => "Blutzucker", :description => "Blutzucker", :video_description => "in der zweiten Lektion erfährst Du, was Hunger auslöst und wie wir das Wissen für unsere Ernährung nutzen können.", 
        :video_id => "GtPOhwY94_w"
        },
      {:id => 3, :name => "Gewicht", :description => "Übergewicht erkennen"},
      {:id => 4, :name => "Zählen", :description => "Kalorienzählen: sinnvoll oder nicht?"},
      {:id => 5, :name => "Alltag", :description => "Ernährungsgewohnheiten ändern"},
      {:id => 6, :name => "Frühstück", :description => "Frühstück"},
      {:id => 7, :name => "Mittags", :description => "Mittagessen"},
      {:id => 8, :name => "Abends", :description => "Abendessen"},
      {:id => 9, :name => "K.hydrate", :description => "Kohlenhydrate"},
      {:id => 10, :name => "Eiweis", :description => "Eiweis"},
      {:id => 11, :name => "Fette", :description => "Fette"},
      {:id => 12, :name => "Vitamine", :description => "Vitamine"},
      {:id => 13, :name => "Getränke", :description => "Getränke"},
      {:id => 14, :name => "Sport", :description => "Sport"},
      {:id => 15, :name => "Fazit", :description => "Fazit aus Staffel 1"}
      ]
  end
end

app/controllers/members/pages_controller.rb
# -*- encoding : utf-8 -*-
class Members::PagesController < Members::ApplicationController
  def index
    current_user.reset_authentication_token!
  end
end

app/controllers/members/pictures_controller.rb
# -*- encoding : utf-8 -*-
class Members::PicturesController < Members::ApplicationController
end

app/controllers/members/profiles_controller.rb
# -*- encoding : utf-8 -*-
class Members::ProfilesController < Members::ApplicationController
	# even a singular resource like account needs a pluralized controller, see http://guides.rubyonrails.org/routing.html#singular-resources

  def show
    @profile = current_user.profile
    @user = current_user
  end

  def new
    current_user.reset_authentication_token!
    @user = current_user
    if @user.profile.nil?
      @user.profile = Profile.new
    end
  end

  def create
    @user = current_user    
    if @user.profile.update_attributes(params[:profile])
      render js: "window.location.pathname='#{members_profile_path}'"
    else
      render js: "alert('Daten Fehlerhaft');"
    end    
  end  
  
end

app/controllers/members/recipes_controller.rb
# -*- encoding : utf-8 -*-
class Members::RecipesController < Members::ApplicationController
end

app/controllers/members/users_controller.rb
# -*- encoding : utf-8 -*-
class Members::UsersController < Members::ApplicationController
	# even a singular resource like account needs a pluralized controller, see http://guides.rubyonrails.org/routing.html#singular-resources  

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to members_profile_path
    else
      # add a error message
      redirect_to members_profile_path
    end
  end
  
end

app/controllers/members/videos_controller.rb
# -*- encoding : utf-8 -*-
class Members::VideosController < Members::ApplicationController
end

app/controllers/members/workouts_controller.rb
# -*- encoding : utf-8 -*-
class Members::WorkoutsController < Members::ApplicationController

  def index
    @workouts = current_user.workouts    
  end

  def create
    workout = Workout.new params[:workout]
    workout.user = current_user

    if workout.save
      redirect_to members_workouts_path
    else
      flash[:warning] = "Fehler beim speichern!"
      redirect_to members_workouts_path
    end
  end
end

app/controllers/members_controller.rb
# -*- encoding : utf-8 -*-
class MembersController < ApplicationController
  layout "internal"
  def index
  end  
end

app/helpers/members/application_helper.rb
# -*- encoding : utf-8 -*-
module Members::ApplicationHelper

  def nav_list_elmement name, url, icon_name
    capture_haml do
      if current_page? url
        haml_tag(:li, :class => :active) do
          haml_tag :a, :href => url do
            haml_tag :i, :class => icon_name
            haml_tag "span.menu-text", name
          end
        end
      else
        haml_tag(:li) do
          haml_tag :a, :href => url do
            haml_tag :i, :class => icon_name
            haml_tag "span.menu-text", name
          end
        end
      end      
    end
  end  

end

app/helpers/members/diaries_helper.rb
# -*- encoding : utf-8 -*-
module Members::DiariesHelper
end

app/helpers/members/pages_helper.rb
# -*- encoding : utf-8 -*-
module Members::PagesHelper
end

app/helpers/members/pictures_helper.rb
# -*- encoding : utf-8 -*-
module Members::PicturesHelper
end

app/helpers/members/profiles_helper.rb
# -*- encoding : utf-8 -*-
module Members::ProfilesHelper
end

app/helpers/members/recipes_helper.rb
# -*- encoding : utf-8 -*-
module Members::RecipesHelper
end

app/helpers/members/videos_helper.rb
# -*- encoding : utf-8 -*-
module Members::VideosHelper
end

app/views/members/profiles/new.haml
.page-header.position-relative
  %h1
    Hallo
    = current_user.firstname
  %small
    Ergänze Deine Daten
.row-fluid
  .span12
    = render "wizard"

app/views/members/profiles/show.haml
- content_for :page_specifc_css do
  / page specific plugin styles
  %link{:href => "/assets/members/jquery-ui-1.10.3.custom.min.css", :rel => "stylesheet"}/
  %link{:href => "/assets/members/jquery.gritter.css", :rel => "stylesheet"}/
  %link{:href => "/assets/members/select2.css", :rel => "stylesheet"}/
  %link{:href => "/assets/members/bootstrap-editable.css", :rel => "stylesheet"}/
  / fonts
  %link{:href => "/assets/members/ace-fonts.css", :rel => "stylesheet"}/
  / ace styles


.page-content
  .page-header.position-relative
    %h1
      Mein Profil
      %small
        %i.icon-double-angle-right
        Einstellungen vornehmen
  / /.page-header
  .row-fluid
    .span12
      / PAGE CONTENT BEGINS              
      .user-profile
        #user-profile-3.user-profile.row-fluid
          .offset1.span10            
            .space
            = form_for @user, :as => :user, :url => members_user_path, :html => {:class => "form-horizontal"} do |f|
            
              .tabbable
                %ul.nav.nav-tabs.padding-16
                  %li.active
                    %a{"data-toggle" => "tab", :href => "#edit-basic"}
                      %i.green.icon-edit.bigger-125
                      mein Profil
                  %li
                    %a{"data-toggle" => "tab", :href => "#edit-settings"}
                      %i.purple.icon-cog.bigger-125
                      Einstellungen
                  %li
                    %a{"data-toggle" => "tab", :href => "#edit-password"}
                      %i.blue.icon-key.bigger-125
                      Passwort
                .tab-content.profile-edit-tab-content
                  #edit-basic.tab-pane.in.active
                    %h4.header.blue.bolder.smaller Allgemein
                    .row-fluid
                      .span4
                        %input{:type => "file"}/
                      .vspace
                      .span8
                        .control-group
                          %label.control-label{:for => "form-field-username"} Vorname
                          .controls                                                        
                            = f.text_field :firstname
                        .control-group
                          %label.control-label{:for => "form-field-first"} Nachname
                          .controls
                            = f.text_field :lastname
                            
                    %hr/
                    .control-group
                      %label.control-label{:for => "form-field-date"} Geburtstag
                      .controls
                        .input-append
                          %input#form-field-date.input-small.date-picker{"data-date-format" => "dd-mm-yyyy", :placeholder => "dd-mm-yyyy", :type => "text", :name => "user[profile_attributes][birthday]", :value => l(@user.profile.birthday)}/
                          %span.add-on
                            %i.icon-calendar
                    .control-group
                      %label.control-label Geschlecht
                      .controls
                        .space-2
                        %label.inline
                          = f.radio_button :gender, "m"
                          %span.lbl männlich
                        \&nbsp; &nbsp; &nbsp;
                        %label.inline
                          = f.radio_button :gender, "w"                          
                          %span.lbl weiblich
                    .space
                    %h4.header.blue.bolder.smaller Kontaktdetails
                    .control-group
                      %label.control-label{:for => "form-field-email"} E-Mail
                      .controls
                        %span.input-icon.input-icon-right
                          = f.email_field :email, :id => "form-field-email"                          
                          %i.icon-envelope
                    = f.fields_for :profile do |profile|
                      .control-group
                        %label.control-label{:for => "form-field-website"} Straße, Hausnummer
                        .controls
                          %span.input-icon.input-icon-right
                            = profile.text_field :street
                            %i.icon-globe
                          %span1
                            = profile.text_field :street_number
                      
                      .control-group
                        %label.control-label{:for => "form-field-phone"} Stadt
                        .controls
                          %span.input-icon.input-icon-right
                            = profile.text_field :city                            
                      .control-group
                        %label.control-label{:for => "form-field-phone"} Land
                        .controls
                          %span.input-icon.input-icon-right
                            = profile.text_field :country     
                      .space
                      
                            
                  #edit-settings.tab-pane
                    .space-10
                    %div
                      %label.inline
                        %input{:name => "form-field-checkbox", :type => "checkbox"}/
                        %span.lbl Make my profile public
                    .space-8
                    %div
                      %label.inline
                        %input{:name => "form-field-checkbox", :type => "checkbox"}/
                        %span.lbl Email me new updates
                    .space-8
                    %div
                      %label.inline
                        %input{:name => "form-field-checkbox", :type => "checkbox"}/
                        %span.lbl Keep a history of my conversations
                      %label.inline
                        %span.space-2.block
                        for
                        %input.input-mini{:maxlength => "3", :type => "text"}/
                        days
                  #edit-password.tab-pane
                    .space-10
                    .control-group
                      %label.control-label{:for => "form-field-pass1"} New Password
                      .controls
                        %input#form-field-pass1{:type => "password"}/
                    .control-group
                      %label.control-label{:for => "form-field-pass2"} Confirm Password
                      .controls
                        %input#form-field-pass2{:type => "password"}/
              .form-actions
                = button_tag(:class => "btn btn-info") do                  
                  %i.icon-ok.bigger-110
                  Save
                
                \&nbsp; &nbsp; &nbsp;
                %button.btn{:type => "reset"}
                  %i.icon-undo.bigger-110
                  Reset
          / /span
        / /user-profile
      / PAGE CONTENT ENDS

- content_for :inline_scripts do          
  /[if lte IE 8]
    <script src="assets/js/excanvas.min.js"></script>
  %script{:src => "/assets/members/jquery-ui-1.10.3.custom.min.js"}
  %script{:src => "/assets/members/jquery.ui.touch-punch.min.js"}
  %script{:src => "/assets/members/jquery.gritter.min.js"}
  %script{:src => "/assets/members/bootbox.min.js"}
  %script{:src => "/assets/members/jquery.slimscroll.min.js"}
  %script{:src => "/assets/members/jquery.easy-pie-chart.min.js"}
  %script{:src => "/assets/members/jquery.hotkeys.min.js"}
  %script{:src => "/assets/members/bootstrap-wysiwyg.min.js"}
  %script{:src => "/assets/members/select2.min.js"}
  
  %script{:src => "/assets/members/fuelux/fuelux.spinner.min.js"}
  %script{:src => "/assets/members/x-editable/bootstrap-editable.min.js"}
  %script{:src => "/assets/members/x-editable/ace-editable.min.js"}
  %script{:src => "/assets/members/jquery.maskedinput.min.js"}
  / ace scripts
  %script{:src => "/assets/members/ace-elements.min.js"}
  %script{:src => "/assets/members/ace.min.js"}
  / inline scripts related to this page
  :javascript
    $(function() {

      $('#form-field-date').datepicker({
        language: "de"
      });
    
    
    	///////////////////////////////////////////
    	$('#user-profile-3')
    	.find('input[type=file]').ace_file_input({
    		style:'well',
    		btn_choose:'Avatar wählen',
    		btn_change:null,
    		no_icon:'icon-picture',
    		thumbnail:'large',
    		droppable:true,
    		before_change: function(files, dropped) {
    			var file = files[0];
    			if(typeof file === "string") {//files is just a file name here (in browsers that don't support FileReader API)
    				if(! (/\.(jpe?g|png|gif)$/i).test(file) ) return false;
    			}
    			else {//file is a File object
    				var type = $.trim(file.type);
    				if( ( type.length > 0 && ! (/^image\/(jpe?g|png|gif)$/i).test(type) )
    						|| ( type.length == 0 && ! (/\.(jpe?g|png|gif)$/i).test(file.name) )//for android default browser!
    					) return false;
    
    				if( file.size > 110000 ) {//~100Kb
    					return false;
    				}
    			}
    
    			return true;
    		}
    	})
    
    
    });

    