config/routes.rb
VitalCoaches::Application.routes.draw do
  get "page/index"

  namespace :members do
    root :to => "pages#index"

    resources :workouts
    
    
    resource :diary
    resources :diary_entries
    resource :profile
    resource :videos do
      resource "nutrition", :only => [:show] do
        get 'lectures/:lecture_id' => 'nutritions#lecture', :as => :lecture
      end
      get "fitness"
      get "motivation"
    end
    resources :pictures
    resources :recipes
    resource :user
  end

  match "ueber_uns" => "page#about", :as => :about
  match "coaches" => "page#coaches", :as => :coaches
  match "agb" => "page#terms", :as => :terms
  match "impressum" => "page#imprint", :as => :imprint

  match "ernaehrungstagebuch" => "page#diary", :as => :diary

  devise_for :users
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
    get "sign_out", :to => "devise/sessions#destroy"
  end

  root :to => 'page#index'

end

app/controllers/members/application_controller.rb
# -*- encoding : utf-8 -*-
class Members::ApplicationController < ApplicationController  
  #layout "internal"
  before_filter :authenticate_user!

  before_filter :check_profile_created

  before_filter :do_breadcrumbs

  helper_method :breadcrumbs

  def breadcrumbs
    @crumbs
  end

  def add_crumb name, url
    @crumbs.push [name, url]    
  end

  private

  def do_breadcrumbs
    @crumbs = []
    @crumbs.push ["Start", members_root_path]    
  end

  def check_profile_created
  	unless request.fullpath == new_members_profile_path
  	  redirect_to new_members_profile_path if current_user.profile.nil?
  	end  	
  end
end

app/controllers/members/diaries_controller.rb
# -*- encoding : utf-8 -*-
class Members::DiariesController < Members::ApplicationController  
  
  def show
    add_crumb "Tagebuch", members_diary_path
    @diary_entries = current_user.diary_entries

    @json_events = []
    @diary_entries.each do |diary_entry|
      @json_events << {:title => "G: #{diary_entry.weight}", :start => diary_entry.entry_date}
    end    

    @json_events = @json_events.to_json
  end

end

app/controllers/members/diary_entries_controller.rb
# -*- encoding : utf-8 -*-
class Members::DiaryEntriesController < Members::ApplicationController  
  
  def create
    diary_entry = DiaryEntry.new params[:diary_entry]
    diary_entry.user = current_user

    if diary_entry.save
      redirect_to members_diary_path
    else
      flash[:warning] = "Fehler beim speichern!"
      redirect_to members_diary_path
    end
  end

end

app/controllers/members/nutritions_controller.rb
# -*- encoding : utf-8 -*-
class Members::NutritionsController < Members::ApplicationController

  before_filter :set_values
  before_filter :set_breadcrumb

  def show    
  end

  def lecture
    add_crumb "Ernährungsvideos", members_videos_nutrition_path

    #render "lektion#{params[:lecture_id]}"
    @lecture = get_lecture params[:lecture_id]
    #@lecture = params[:lecture_id]
    render "lecture"
  end

  private

  def get_lecture id    
    result = nil
    @lecutures.each do |lecture|
      result = lecture if lecture[:id] == id.to_i
    end
    result
  end

  def set_breadcrumb
    add_crumb "Videos", members_videos_nutrition_path
    
  end

  def set_values
    @lecutures = [
      {:id => 1, :name => "JoJo-Effekt", :description => "JoJo-Effekt verhindern; warum Diäten nicht funktionieren", :video_description => 
        "In der ersten Video-Lektion führen wir Dich in die Grundlagen ein. Nachdem Du das Video zu Ende gesehen hast beginnt das Quiz. Dort wird mit einfachen Fragen abgeprüft, ob Du auch gut zugesehen hast :)", 
        :video_id => "5OVT2bVwIBE"
      },
      {:id => 2, :name => "Blutzucker", :description => "Blutzucker", :video_description => "in der zweiten Lektion erfährst Du, was Hunger auslöst und wie wir das Wissen für unsere Ernährung nutzen können.", 
        :video_id => "GtPOhwY94_w"
        },
      {:id => 3, :name => "Gewicht", :description => "Übergewicht erkennen"},
      {:id => 4, :name => "Zählen", :description => "Kalorienzählen: sinnvoll oder nicht?"},
      {:id => 5, :name => "Alltag", :description => "Ernährungsgewohnheiten ändern"},
      {:id => 6, :name => "Frühstück", :description => "Frühstück"},
      {:id => 7, :name => "Mittags", :description => "Mittagessen"},
      {:id => 8, :name => "Abends", :description => "Abendessen"},
      {:id => 9, :name => "K.hydrate", :description => "Kohlenhydrate"},
      {:id => 10, :name => "Eiweis", :description => "Eiweis"},
      {:id => 11, :name => "Fette", :description => "Fette"},
      {:id => 12, :name => "Vitamine", :description => "Vitamine"},
      {:id => 13, :name => "Getränke", :description => "Getränke"},
      {:id => 14, :name => "Sport", :description => "Sport"},
      {:id => 15, :name => "Fazit", :description => "Fazit aus Staffel 1"}
      ]
  end
end

app/controllers/members/pages_controller.rb
# -*- encoding : utf-8 -*-
class Members::PagesController < Members::ApplicationController
  def index
    current_user.reset_authentication_token!
  end
end

app/controllers/members/pictures_controller.rb
# -*- encoding : utf-8 -*-
class Members::PicturesController < Members::ApplicationController
end

app/controllers/members/profiles_controller.rb
# -*- encoding : utf-8 -*-
class Members::ProfilesController < Members::ApplicationController
	# even a singular resource like account needs a pluralized controller, see http://guides.rubyonrails.org/routing.html#singular-resources

  def show
    @profile = current_user.profile
    @user = current_user
  end

  def new
    current_user.reset_authentication_token!
    @user = current_user
    if @user.profile.nil?
      @user.profile = Profile.new
    end
  end

  def create
    @user = current_user    
    if @user.profile.update_attributes(params[:profile])
      render js: "window.location.pathname='#{members_profile_path}'"
    else
      render js: "alert('Daten Fehlerhaft');"
    end    
  end  
  
end

app/controllers/members/recipes_controller.rb
# -*- encoding : utf-8 -*-
class Members::RecipesController < Members::ApplicationController
end

app/controllers/members/users_controller.rb
# -*- encoding : utf-8 -*-
class Members::UsersController < Members::ApplicationController
	# even a singular resource like account needs a pluralized controller, see http://guides.rubyonrails.org/routing.html#singular-resources  

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to members_profile_path
    else
      # add a error message
      redirect_to members_profile_path
    end
  end
  
end

app/controllers/members/videos_controller.rb
# -*- encoding : utf-8 -*-
class Members::VideosController < Members::ApplicationController
end

app/controllers/members/workouts_controller.rb
# -*- encoding : utf-8 -*-
class Members::WorkoutsController < Members::ApplicationController

  def index
    @workouts = current_user.workouts    
  end

  def create
    workout = Workout.new params[:workout]
    workout.user = current_user

    if workout.save
      redirect_to members_workouts_path
    else
      flash[:warning] = "Fehler beim speichern!"
      redirect_to members_workouts_path
    end
  end
end

app/controllers/members_controller.rb
# -*- encoding : utf-8 -*-
class MembersController < ApplicationController
  layout "internal"
  def index
  end  
end

app/helpers/members/application_helper.rb
# -*- encoding : utf-8 -*-
module Members::ApplicationHelper

  def nav_list_elmement name, url, icon_name
    capture_haml do
      if current_page? url
        haml_tag(:li, :class => :active) do
          haml_tag :a, :href => url do
            haml_tag :i, :class => icon_name
            haml_tag "span.menu-text", name
          end
        end
      else
        haml_tag(:li) do
          haml_tag :a, :href => url do
            haml_tag :i, :class => icon_name
            haml_tag "span.menu-text", name
          end
        end
      end      
    end
  end  

end

app/helpers/members/diaries_helper.rb
# -*- encoding : utf-8 -*-
module Members::DiariesHelper
end

app/helpers/members/pages_helper.rb
# -*- encoding : utf-8 -*-
module Members::PagesHelper
end

app/helpers/members/pictures_helper.rb
# -*- encoding : utf-8 -*-
module Members::PicturesHelper
end

app/helpers/members/profiles_helper.rb
# -*- encoding : utf-8 -*-
module Members::ProfilesHelper
end

app/helpers/members/recipes_helper.rb
# -*- encoding : utf-8 -*-
module Members::RecipesHelper
end

app/helpers/members/videos_helper.rb
# -*- encoding : utf-8 -*-
module Members::VideosHelper
end

app/views/layouts/members/_ace_settings.html.haml
#ace-settings-container.ace-settings-container
          #ace-settings-btn.btn.btn-app.btn-mini.btn-warning.ace-settings-btn
            %i.icon-cog.bigger-150
          #ace-settings-box.ace-settings-box
            %div
              .pull-left
                %select#skin-colorpicker.hide
                  %option{"data-class" => "default", :value => "#438EB9"} #438EB9
                  %option{"data-class" => "skin-1", :value => "#222A2D"} #222A2D
                  %option{"data-class" => "skin-2", :value => "#C6487E"} #C6487E
                  %option{"data-class" => "skin-3", :value => "#D0D0D0"} #D0D0D0
              %span &nbsp; Choose Skin
            %div
              %input#ace-settings-header.ace-checkbox-2{:type => "checkbox"}/
              %label.lbl{:for => "ace-settings-header"} Fixed Header
            %div
              %input#ace-settings-sidebar.ace-checkbox-2{:type => "checkbox"}/
              %label.lbl{:for => "ace-settings-sidebar"} Fixed Sidebar
            %div
              %input#ace-settings-breadcrumbs.ace-checkbox-2{:type => "checkbox"}/
              %label.lbl{:for => "ace-settings-breadcrumbs"} Fixed Breadcrumbs
            %div
              %input#ace-settings-rtl.ace-checkbox-2{:type => "checkbox"}/
              %label.lbl{:for => "ace-settings-rtl"} Right To Left (rtl)
        / /#ace-settings-container

app/views/layouts/members/_breadcrumbs.html.haml
#breadcrumbs.breadcrumbs
  %ul.breadcrumb
    %li
      %i.icon-home.home-icon
      = link_to @crumbs[0][0], @crumbs[0][1]
      %span.divider
        %i.icon-angle-right.arrow-icon
    - @crumbs[1..@crumbs.size].each do |crumb|
      %li
        = link_to crumb[0], crumb[1]
        %span.divider
          %i.icon-angle-right.arrow-icon
    %li.active aktuelle Seite
  / .breadcrumb
  // = render "layouts/members/search"

app/views/layouts/members/_navbar.html.haml
.navbar
  .navbar-inner
    .container-fluid
      %a.brand{:href => "#{members_root_path}"}
        %small
          %i.icon-leaf
          Vital Coaches
      / /.brand
      %ul.nav.ace-nav.pull-right
        %li.grey
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %i.icon-tasks
            %span.badge.badge-grey 4
          %ul.pull-right.dropdown-navbar.dropdown-menu.dropdown-caret.dropdown-closer
            %li.nav-header
              %i.icon-ok
              4 Aufgaben zu erledigen
            %li
              %a{:href => "#"}
              .clearfix
                %span.pull-left Trinken
                %span.pull-right 65%
              .progress.progress-mini
                .bar{:style => "width:65%"}
            %li
              %a{:href => "#"}
              .clearfix
                %span.pull-left Fitness
                %span.pull-right 35%
              .progress.progress-mini.progress-danger
                .bar{:style => "width:35%"}
            %li
              %a{:href => "#"}
              .clearfix
                %span.pull-left Protokollieren
                %span.pull-right 15%
              .progress.progress-mini.progress-warning
                .bar{:style => "width:15%"}
            %li
              %a{:href => "#"}
              .clearfix
                %span.pull-left Lektionen pauken
                %span.pull-right 90%
              .progress.progress-mini.progress-success.progress-striped.active
                .bar{:style => "width:90%"}
            %li
              %a{:href => "#"}
                hier gehts zur Aufgabenliste
                %i.icon-arrow-right
        %li.purple
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %i.icon-bell-alt.icon-animated-bell
            %span.badge.badge-important 8
          %ul.pull-right.dropdown-navbar.navbar-pink.dropdown-menu.dropdown-caret.dropdown-closer
            %li.nav-header
              %i.icon-warning-sign
              8 Meldungen
            %li
              %a{:href => "#"}
              .clearfix
                %span.pull-left
                  %i.btn.btn-mini.no-hover.btn-pink.icon-comment
                  Neue Kommentare
                %span.pull-right.badge.badge-info +12
            %li
              %a{:href => "#"}
                %i.btn.btn-mini.btn-primary.icon-user
                Edgar hat sich soeben eingeloggt...
            %li
              %a{:href => "#"}
              .clearfix
                %span.pull-left
                  %i.btn.btn-mini.no-hover.btn-success.icon-shopping-cart
                  neue Einkaufslisten
                %span.pull-right.badge.badge-success +8
            %li
              %a{:href => "#"}
              .clearfix
                %span.pull-left
                  %i.btn.btn-mini.no-hover.btn-info.icon-twitter
                  neue Mitglieder
                %span.pull-right.badge.badge-info +11
            %li
              %a{:href => "#"}
                Alle Nachrichten ansehen
                %i.icon-arrow-right
        %li.green
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %i.icon-envelope.icon-animated-vertical
            %span.badge.badge-success 5
          %ul.pull-right.dropdown-navbar.dropdown-menu.dropdown-caret.dropdown-closer
            %li.nav-header
              %i.icon-envelope-alt
              5 Nachrichten
            %li
              %a{:href => "#"}
                %img.msg-photo{:alt => "Alex's Avatar", :src => "/assets/members/avatars/avatar.png"}/
                %span.msg-body
                  %span.msg-title
                    %span.blue Alex:
                    Hey, hab wieder ein Kilo abgenommen ...
                  %span.msg-time
                    %i.icon-time
                    %span gerade eben
            %li
              %a{:href => "#"}
                %img.msg-photo{:alt => "Susan's Avatar", :src => "/assets/members/avatars/avatar3.png"}/
                %span.msg-body
                  %span.msg-title
                    %span.blue Edgar:
                    Klasse, weiter so ...
                  %span.msg-time
                    %i.icon-time
                    %span vor 20 Minuten
            %li
              %a{:href => "#"}
                %img.msg-photo{:alt => "Bob's Avatar", :src => "/assets/members/avatars/avatar4.png"}/
                %span.msg-body
                  %span.msg-title
                    %span.blue Bob:
                    Nullam quis risus eget urna mollis ornare ...
                  %span.msg-time
                    %i.icon-time
                    %span 3:15 pm
            %li
              %a{:href => "#"}
                Alle Nachrichten anschauen
                %i.icon-arrow-right
        %li.light-blue
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %img.nav-user-photo{:alt => "Jason's Photo", :src => "/assets/members/avatars/user.jpg"}/
            %span.user-info
              %small Hallo,
              = current_user.firstname
            %i.icon-caret-down
          %ul.user-menu.pull-right.dropdown-menu.dropdown-yellow.dropdown-caret.dropdown-closer
            %li
              %a{:href => "#"}
                %i.icon-cog
                Einstellungen
            %li
              %a{:href => members_profile_path}
                %i.icon-user
                Profil
            %li.divider
            %li
              = link_to sign_out_path do              
                %i.icon-off
                Logout
      / /.ace-nav
    / /.container-fluid
  / /.navbar-inner

app/views/layouts/members/_search.html.haml
#nav-search.nav-search
    %form.form-search
      %span.input-icon
        %input#nav-search-input.input-small.nav-search-input{:autocomplete => "off", :placeholder => "Suche ...", :type => "text"}/
        %i.icon-search.nav-search-icon
  / #nav-search

app/views/layouts/members/_sidebar.html.haml
#sidebar.sidebar
  #sidebar-shortcuts.sidebar-shortcuts
    #sidebar-shortcuts-large.sidebar-shortcuts-large
      %button.btn.btn-small.btn-success
        %i.icon-signal
      %button.btn.btn-small.btn-info
        %i.icon-pencil
      %button.btn.btn-small.btn-warning
        %i.icon-group
      %button.btn.btn-small.btn-danger
        %i.icon-cogs
    #sidebar-shortcuts-mini.sidebar-shortcuts-mini
      %span.btn.btn-success
      %span.btn.btn-info
      %span.btn.btn-warning
      %span.btn.btn-danger
  / #sidebar-shortcuts
  %ul.nav.nav-list
    = nav_list_elmement "Übersichtsseite", members_root_path, "icon-dashboard"
    %li
      %a.dropdown-toggle{:href => "#"}
        %i.icon-desktop
        %span.menu-text Videos
        %span.badge.badge-primary 15
        %b.arrow.icon-angle-down
      %ul.submenu
        = nav_list_elmement "Ernährungsvideos", members_videos_nutrition_path, "icon-double-angle-right"
        = nav_list_elmement "Fitnessvideos", fitness_members_videos_path, "icon-double-angle-right"
        = nav_list_elmement "Motivationsvideos", motivation_members_videos_path, "icon-double-angle-right"       
    
    = # nav_list_elmement "Rezepte", members_recipes_path, "icon-list-alt"   

    %li
      %a.dropdown-toggle{:href => "#"}
        %i.icon-desktop
        %span.menu-text meine Tagebücher
        %span.badge.badge-primary
        %b.arrow.icon-angle-down
      %ul.submenu
        = # nav_list_elmement "Ernährungs-Tagebuch", members_diary_path, "icon-edit"
        = nav_list_elmement "Trainings-Tagebuch", members_workouts_path, "icon-edit"
        = # nav_list_elmement "Gewichts-Tagebuch", members_diary_path, "icon-edit"


    = nav_list_elmement "meine Bilder", members_pictures_path, "icon-picture"    
    %li
      %a.dropdown-toggle{:href => "#"}
        %i.icon-tag
        %span.menu-text Community
        %b.arrow.icon-angle-down
      %ul.submenu
        %li
          %a{:href => "profile.html"}
            %i.icon-double-angle-right
            Mitglieder
        %li
          %a{:href => "pricing.html"}
            %i.icon-double-angle-right
            Forum        
    %li.open
      %a.dropdown-toggle{:href => "#"}
        %i.icon-file-alt
        %span.menu-text
          mein Profil
          
        %b.arrow.icon-angle-down
      %ul.submenu
        %li
          = link_to members_profile_path do
            %i.icon-double-angle-right
            persönliche Daten
        %li
          %a{:href => "error-500.html"}
            %i.icon-double-angle-right
            Mitgliedschaft
        %li
          %a{:href => "grid.html"}
            %i.icon-double-angle-right
            Nachrichten
            %span.badge 4
        %li
          %a{:href => "blank.html"}
            %i.icon-double-angle-right
            Coaches
  / /.nav-list
  #sidebar-collapse.sidebar-collapse
    %i.icon-double-angle-left

app/views/layouts/members/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title Willkommen bei Vital Coaches
    %meta{:content => "", :name => "description"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    / basic styles
    = stylesheet_link_tag "members/application"
    = stylesheet_link_tag "members/bootstrap.min", "members/bootstrap-responsive.min", "members/font-awesome.min"
    
    /[if IE 7]
      = stylesheet_link_tag "members/font-awesome-ie7.min"
      
    / page specific plugin styles
    = yield :page_specifc_css
    / fonts
    = stylesheet_link_tag "members/ace-fonts"
    
    / ace styles
    = stylesheet_link_tag "members/ace.min", "members/ace-responsive.min", "members/ace-skins.min"
    
    /[if lte IE 8]
      = stylesheet_link_tag "members/ace-ie.min"
    / inline styles related to this page
  %body
    = render "layouts/members/navbar"
    .main-container.container-fluid
      %a#menu-toggler.menu-toggler{:href => "#"}
        %span.menu-text
      = render "layouts/members/sidebar"
      .main-content
        = render "layouts/members/breadcrumbs"
        .page-content
          .row-fluid
            .span12
              / PAGE CONTENT BEGINS
              = yield
              / PAGE CONTENT ENDS
            / /.span
          / /.row-fluid
        / /.page-content
        
      / /.main-content
    / /.main-container
    %a#btn-scroll-up.btn-scroll-up.btn.btn-small.btn-inverse{:href => "#"}
      %i.icon-double-angle-up.icon-only.bigger-110
    / basic scripts
    / [if !IE]>
    :javascript
      window.jQuery || document.write("<script src='/assets/members/jquery-2.0.3.min.js'>"+"<"+"/script>");
    / <![endif]
    /[if IE]
      <script type="text/javascript">
      window.jQuery || document.write("<script src='/assets/members/jquery-1.10.2.min.js'>"+"<"+"/script>");
      </script>
    :javascript
      if("ontouchend" in document) document.write("<script src='/assets/members/jquery.mobile.custom.min.js'>"+"<"+"/script>");
    %script{:src => "/assets/members/bootstrap.min.js"}
    / page specific plugin scripts
    = yield :scripts
    = render "layouts/google_analytics"
    / ace scripts
    %script{:src => "/assets/members/ace-elements.min.js"}
    %script{:src => "/assets/members/ace.min.js"}
    / inline scripts related to this page
    = yield :inline_scripts