config/routes.rb
VitalCoaches::Application.routes.draw do
  get "page/index"

  namespace :members do
    root :to => "pages#index"

    resources :workouts
    
    
    resource :diary
    resources :diary_entries
    resource :profile
    resource :videos do
      resource "nutrition", :only => [:show] do
        get 'lectures/:lecture_id' => 'nutritions#lecture', :as => :lecture
      end
      get "fitness"
      get "motivation"
    end
    resources :pictures
    resources :recipes
    resource :user
  end

  match "ueber_uns" => "page#about", :as => :about
  match "coaches" => "page#coaches", :as => :coaches
  match "agb" => "page#terms", :as => :terms
  match "impressum" => "page#imprint", :as => :imprint

  match "ernaehrungstagebuch" => "page#diary", :as => :diary

  devise_for :users
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
    get "sign_out", :to => "devise/sessions#destroy"
  end

  root :to => 'page#index'

end

app/models/diary_entry.rb
class DiaryEntry < ActiveRecord::Base
  belongs_to :user
  attr_accessible :entry_date, :weight, :weight
end

app/models/lecture.rb
# -*- encoding : utf-8 -*-
class Lecture
  attr_accessor :name, :description, :id
end

app/models/profile.rb
# -*- encoding : utf-8 -*-
class Profile < ActiveRecord::Base
  belongs_to :user
  store :anamnesis, accessors: [:already_did_diets, :fruits_frequency, :fastfood_frequency, :snacks_frequency, :cooking,
    :personal_activity, :sports_frequency, :target], coder: JSON
  attr_accessible :abdominal_measurement, :bank_account, :bank_account_owner, 
    :bank_code, :bank_name, :birthday, :body_height, :city, :country, :street, :street_number, :weight, :weight, :zipcode, :already_did_diets, :fruits_frequency, :fastfood_frequency, :snacks_frequency, :cooking,
    :personal_activity, :sports_frequency, :target


    def birthday
    	if read_attribute(:birthday).nil?
    		return Date.today
    	else
    		read_attribute :birthday
    	end
    end
end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, 
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :gender, :firstname, :lastname, :profile_attributes
  # attr_accessible :title, :body
  has_one :profile
  has_many :diary_entries
  has_many :workouts

  accepts_nested_attributes_for :profile
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :user
  attr_accessible :title
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(user)
    members_root_url
  end
  
end

app/controllers/members/pages_controller.rb
# -*- encoding : utf-8 -*-
class Members::PagesController < Members::ApplicationController
  def index
    current_user.reset_authentication_token!
  end
end

app/controllers/members/users_controller.rb
# -*- encoding : utf-8 -*-
class Members::UsersController < Members::ApplicationController
	# even a singular resource like account needs a pluralized controller, see http://guides.rubyonrails.org/routing.html#singular-resources  

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to members_profile_path
    else
      # add a error message
      redirect_to members_profile_path
    end
  end
  
end

app/controllers/members/videos_controller.rb
# -*- encoding : utf-8 -*-
class Members::VideosController < Members::ApplicationController
end

app/controllers/members_controller.rb
# -*- encoding : utf-8 -*-
class MembersController < ApplicationController
  layout "internal"
  def index
  end  
end

app/controllers/page_controller.rb
# -*- encoding : utf-8 -*-
class PageController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper


  def title page_title
    @title = page_title
  end
end

app/helpers/members/application_helper.rb
# -*- encoding : utf-8 -*-
module Members::ApplicationHelper

  def nav_list_elmement name, url, icon_name
    capture_haml do
      if current_page? url
        haml_tag(:li, :class => :active) do
          haml_tag :a, :href => url do
            haml_tag :i, :class => icon_name
            haml_tag "span.menu-text", name
          end
        end
      else
        haml_tag(:li) do
          haml_tag :a, :href => url do
            haml_tag :i, :class => icon_name
            haml_tag "span.menu-text", name
          end
        end
      end      
    end
  end  

end

app/helpers/members/diaries_helper.rb
# -*- encoding : utf-8 -*-
module Members::DiariesHelper
end

app/helpers/members/pages_helper.rb
# -*- encoding : utf-8 -*-
module Members::PagesHelper
end

app/helpers/members/pictures_helper.rb
# -*- encoding : utf-8 -*-
module Members::PicturesHelper
end

app/helpers/members/profiles_helper.rb
# -*- encoding : utf-8 -*-
module Members::ProfilesHelper
end

app/helpers/members/recipes_helper.rb
# -*- encoding : utf-8 -*-
module Members::RecipesHelper
end

app/helpers/members/videos_helper.rb
# -*- encoding : utf-8 -*-
module Members::VideosHelper
end

app/helpers/page_helper.rb
# -*- encoding : utf-8 -*-
module PageHelper
end

app/views/layouts/_google_analytics.html.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  
    ga('create', 'UA-41510480-1', 'vital-coaches.de');
    ga('send', 'pageview');

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title 
      = @title || "Vital Coaches Video Coaching"
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    = yield :meta_tags
    / Le styles
    = stylesheet_link_tag "application"
    
    / Le HTML5 shim, for IE6-8 support of HTML5 elements
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    / Le fav and touch icons
    %link{:href => "apple-touch-icon-144-precomposed.png", :rel => "apple-touch-icon-precomposed", :sizes => "144x144"}/
    %link{:href => "apple-touch-icon-114-precomposed.png", :rel => "apple-touch-icon-precomposed", :sizes => "114x114"}/
    %link{:href => "apple-touch-icon-72-precomposed.png", :rel => "apple-touch-icon-precomposed", :sizes => "72x72"}/
    %link{:href => "apple-touch-icon-57-precomposed.png", :rel => "apple-touch-icon-precomposed"}/
    
    = favicon_link_tag "favicon.png"
  %body
    / ################ NAVIGATION START ################
    .navbar-wrapper
      #navigation.navbar.navbar-fixed-top
        .navbar-inner
          .container
            %button.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse", :type => "button"}
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.brand{:href => "/"}
              = image_tag "logo.png"              
            .nav-collapse.collapse
              %ul.nav.pull-right
                %li.active
                  %a{:href => "/"} Start
                %li
                  %a{:href => "/#features"} Leistungen                
                %li
                  %a{:href => "/#testimonials"} Userstimmen
                %li
                  = link_to "Coaches", coaches_path                  
                %li
                  = link_to "Gründer", about_path
                %li
                  = link_to "Registrieren", new_user_registration_path
                %li
                  = link_to "Einloggen", sign_in_path
                  
    / ################ NAVIGATION END ################
    / ################ WRAP START ################
    #wrap
      = yield
     
      / ################ PUSH WILL KEEP THE FOOTER AT BOTTOM IF YOU WANT TO CREATE OTHER PAGES ################
      #push
    / ################ FOOTER START ################
    %footer#footer.margintop20
      .container
        .row
          .span4
            %h2 über uns...
            = image_tag "logo.png"            
            %p Ernährungsberatung seit 10 Jahren. Online-Coaching seit 2013.
            %p.copyright
              © 2013 Vital Coaches.
          .span2
            %h2 links
            %ul.unstyled.margintop20
              %li 
                = link_to "Über uns", about_path
              %li Blog
              %li Geschichte
              %li
                = link_to "Coaches", coaches_path
          .span3
            %h2 Newsletter
            .input-append.margintop20
              %input#appendedInputButton.span2{:placeholder => "deine E-Mailadresse..", :type => "text"}/
              %button#newsletter.btn{:type => "button"} abonnieren!
            %ul.inline.social.margintop20
              %li
                %i.icon-facebook
              %li
                %i.icon-twitter
              %li
                %i.icon-linkedin
          .span3
            %h2
              tweets
              %i.icon-twitter
            %ul#twitter.margintop20
    / ################ FOOTER END ################
    / ################ JAVASCRIPTS ################
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"   
    = render "layouts/google_analytics"
    :javascript      
      $('#more_infos_button_top').on('click', function() {
        ga('send', 'event', 'button', 'click', 'more_infos_button_top');
      });
      $('#more_infos_button_bottom').on('click', function() {
        ga('send', 'event', 'button', 'click', 'more_infos_button_bottom');
      });
      $('#newsletter').on('click', function() {
        ga('send', 'event', 'button', 'click', 'newsletter');
      });
= yield :inline_scripts

app/views/layouts/internal.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title Vital Coaches Video Coaching
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    / Le styles
    = stylesheet_link_tag "application"
    
    / Le HTML5 shim, for IE6-8 support of HTML5 elements
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    / Le fav and touch icons
    %link{:href => "apple-touch-icon-144-precomposed.png", :rel => "apple-touch-icon-precomposed", :sizes => "144x144"}/
    %link{:href => "apple-touch-icon-114-precomposed.png", :rel => "apple-touch-icon-precomposed", :sizes => "114x114"}/
    %link{:href => "apple-touch-icon-72-precomposed.png", :rel => "apple-touch-icon-precomposed", :sizes => "72x72"}/
    %link{:href => "apple-touch-icon-57-precomposed.png", :rel => "apple-touch-icon-precomposed"}/
    %link{:href => "favicon.png", :rel => "shortcut icon"}/
  %body
    / ################ NAVIGATION START ################
    .navbar-wrapper
      #navigation.navbar.navbar-fixed-top
        .navbar-inner
          .container
            %button.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse", :type => "button"}
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.brand{:href => "/"}
              = image_tag "logo.png"              
            .nav-collapse.collapse
              %ul.nav.pull-right
                %li.active
                  %a{:href => "/"} Home
                %li
                  %a{:href => "#"} Ernährung
                %li
                  %a{:href => "#"} Fitness
                %li
                  %a{:href => "#"} Motivation                
                  
    / ################ NAVIGATION END ################
    / ################ WRAP START ################
    #wrap
      = yield
     
      / ################ PUSH WILL KEEP THE FOOTER AT BOTTOM IF YOU WANT TO CREATE OTHER PAGES ################
      #push
    / ################ FOOTER START ################
    %footer#footer.margintop20
      .container
        .row
        
    / ################ FOOTER END ################
    / ################ JAVASCRIPTS ################
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"   
    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      
        ga('create', 'UA-41510480-1', 'vital-coaches.de');
        ga('send', 'pageview');
      
      $('#more_infos_button_top').on('click', function() {
        ga('send', 'event', 'button', 'click', 'more_infos_button_top');
      });
      $('#more_infos_button_bottom').on('click', function() {
        ga('send', 'event', 'button', 'click', 'more_infos_button_bottom');
      });
      $('#newsletter').on('click', function() {
        ga('send', 'event', 'button', 'click', 'newsletter');
      });

app/views/page/_video_startpage.html.erb
<script>      
  var tag = document.createElement('script');

  tag.src = "https://www.youtube.com/iframe_api";
  var firstScriptTag = document.getElementsByTagName('script')[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);      

  var player_width = $("#player").css("width");      

  var player;
  function onYouTubeIframeAPIReady() {
    player = new YT.Player('player', {
      height: '390',
      width: player_width,
      videoId: 'UBUXMgZieV8',
      
    });
  }      
</script>

app/views/page/about.html.haml
/ ################ HEADER START ################
%header#top
  .container.home
    .row
      .span12
        %h1 die Macher
        %h2 Vital Coaches - das sind wir.
        %p
          Aus der Idee, mehr Menschen auf einmal helfen zu können als es in einem Kurs vor Ort möglich wäre, enstand die Online-Variante der Ernährungsberatung.
/ ################ HEADER END ################
.container
  %section#testimonials
    .row.center
      %h2
        die Macher
        %i.icon-thumbs-up
      .span6.margintop20
        = image_tag "edgar.png"              
        %hr/
        %blockquote
          "Nach meinem Studium der Ökotrophologie arbeitete ich viele Jahre in der Offline-Welt als Ernährungsberater. In einem Fitness-Studio erstellte ich ein Ernährungskonzept für gesunde, ausgewogene Ernährung. Ich gab erfolgreich Kurse und bildete zusätzlich Diätassistenten aus."
        %cite
          Edgar, Dipl.-Oecotroph.
      .span6.margintop20
        = image_tag "alex.png"              
        %hr/
        %blockquote
          "Als ich mit 12 meinen ersten Computer bekam war es um mich geschehen: mir 13 schrieb ich die ersten, einfachen Programme auf meinem Amiga mit BASIC. Mit 14 die ersten Spiele auf einem 486er in QuickBasic, mit 16 Tools und Spiele mit TurboPascal... und es endete mit dem Informatik-Studium an der Uni Karlsruhe. Nun entwickle ich Web-Anwendungen mit Ruby on Rails."
        %cite
          Alex, Dipl. Informatiker
      

  %hr.line/

app/views/page/coaches.haml
/ ################ HEADER START ################
%header#top
  .container.home
    .row
      .span12
        %h1 die Coaches
        %h2 Ernährung, Aktivität, Motivation
        %p Wir unterstützen Dich auf deinem Weg zum Wunschgewicht. Gemeinsam sind wir erfolgreich.
/ ################ HEADER END ################
.container
  %section#testimonials
    .row.center
      %h2
        Vital Coaches Team
        %i.icon-thumbs-up
      .span3.margintop20
        = image_tag "edgar.png"              
        %hr/
        %blockquote
          "Nach meinem Studium der Ökotrophologie arbeitete ich viele Jahr in der Offline-Welt als Ernährungsberater. In einem Fitness-Studio erstellte ich ein Ernährungskonzept für gesunde, ausgewogene Ernährung. Ich gab erfolgreich Kurse und bildete zusätzlich Diätassistenten aus."
        %cite
          Edgar, Dipl.-Oecotroph.
      .span3.margintop20
        = image_tag "p2.png"              
        %hr/
        %blockquote
          - #          "Im Alter von 18 Jahren begann ich mit viel Begeisterung im heimischen Fitnessclub zu arbeiten. Als Aerobic-Trainerin und Kursleiterin für Rückenprävention konnte ich viele Menschen motivieren ihre Gesundheit zu stärken. Mit meiner eigenen kleinen TV-Sendung für Body-Shape und Wirbelsäulengymnastik erreichte ich nun auch die Menschen vor den Fernsehern. Später leitete ich Ernährungsseminare in den USA und baute einen Open Air Fitness Club in Griechenland auf. Bis heute bin ich als Firmen-Beraterin im Bereich Innovatives Gesundheitstraining tätig. "
          "als Personal Trainer motiviere ich Menschen und helfen Ihnen dabei, ihre Ziele zu erreichen. Durch meine Ausbildung im Fitness-Studio und meiner langjährigen Praxiserfahrung als Personal Coach weiß ich, worauf es ankommt. Ich begleite aktiv dabei, richtig Sport zu machen."
        %cite
          - #Eileen, Personal Trainer
          Petra, Personal Trainer
      .span3.margintop20
        = image_tag "p3.png"              
        %hr/
        %blockquote
          "In einem gesunde Körper steckt ein gesunder Geist. Aber auch umgekehrt muss ein gesunder Geist gehegt und gepflegt werden. Ich arbeite seit Jahren mit Menschen, die sich bei Alltagsprobleme helfen lassen wollen und ihnen dabei die nötige Ausdauer fehlt. Das Thema Motivation spielt hier die entscheidende Rolle. Ich helfe Dir, deine Ziele zu erreichen."        
        %cite
          Sarah, Dip. Psychologin          
      .span3.margintop20
        = image_tag "p4.png"
        %hr/
        %blockquote
          "Als ich vor 5 Jahren zu Pilates fand wusste ich: es ist Liebe auf den ersten Blick. Mein Hobby wurde zum Beruf. Seit meiner Ausbildung als Trainer gebe ich Personal Training."
        %cite
          Frank, Pilates Trainer
  / ################ TESTIMONIALS  SECTION END ################
  %hr.line/

app/views/page/diary.haml
- title "Ernährungstagebuch"
/ ################ HEADER START ################
%header#top
  .container.home
    .row
      .span12
        %h1 Ernährungstagebuch
        %p behalte den Überblick.
/ ################ HEADER END ################
.container
  %section
    .row
      .span6
        %h2 führe Dein Tagebuch        
        %p
          Um zu wissen wo wir ansetzen können ist es hilfreich, wenn Du regelmäßig aufschreibst, was Du isst. Hierzu haben wir Dir ein einfach zu bedienendes Tool gebaut, mit dem Du Deine Malzeiten einfach eintragen kannst.       
      .span6
        = image_tag "diary1.png", :alt => "Ernährungstagebuch Screenshot 1"

    .row
      .span6
        = image_tag "diary.png", :alt => "Ernährungstagebuch Screenshot 2"
      .span6
        %h2 und behalte den Überblick
        %p
          So hast Du den Überblick über Deine Ernährungsgewohnheit - und wenn Du willst kannst Du die Daten mit Deinem Coach teilen. Andernfalls bleiben Sie nur für Dich privat einsehbar.
      
      

  %hr.line/

app/views/page/imprint.haml
%header#top
  .container.home
    .row
      .span12
        %h1 Impressum
.container
  .row
    .span12
      #imprint        
        %p G.Consulting
        %p Reinhold-Schneider-Str. 76
        %p 76199 Karlsruhe
        %p Deutschland
        %p Steuernummer: 35078/08641
        %p info@gconsulting.de
        %p Datum: 1. November 2013
= content_for :meta_tags do
  %meta{:content => "noindex", :name => "robots"}

app/views/page/index.html.haml
/ ################ HEADER START ################
%header#top
  .container.home
    .row
      .span6
        %h1 Wie nehme ich gesund ab und halte mein Gewicht dauerhaft?        
        %p gesund Abnehmen leicht gemacht: wir erklären Dir Schritt für Schritt wie es funktioniert.
        %p
          = link_to "Registrieren und 14 Tage kostenlos testen", new_user_registration_path, :class => "btn btn-landing btn-large", :id => "more_infos_button_top"          
      #main-media.span6.margintop20
        #player      
        
        
/ ################ HEADER END ################
/ ################ MAIN CONTAINER START ################
.container
  / ################ FEATURES SECTION START ################
  %section#features
    .row
      .span6
        %h1 Vital Coaches
        %h3 interaktives online video coaching
        %p
          Bei
          %span Vital Coaches
          lernst Du Schritt für Schritt, wie gesunde Ernährung funktioniert. Wir haben unsere langjährige Erfahrung, die wir beim Abhalten von Ernährungskursen perfektioniert haben, in Video-Lektionen gepackt.
        %p
          Lerne noch heute auf einfachem Weg, wie Du Dich dauerhaft gesund ernährst. So erreichst Du Dein Traumgewicht und kannst es auch auf Dauer halten. Mit unseren verständlichen Video-Lektionen nehmen wir Dich an die Hand und erklären Dir Schritt für Schritt, wie Du Dein Wunschgewicht erreichen wirst.
      .span6
        = image_tag "person.png"              
    .row.margintop20
      .span4
        %h2
          %i.icon-briefcase
          einfache Lektionen
        %p Fundierte wissenschaftliche Erkenntnise, für Dich in einfachen Video-Lektionen aufbereitet. Unsere Experten erklären anhand von praktischen Beispielen, wie Du Deine Ernährung richtig umstellst - ohne komplizierte Fachausdrücke!
      / /span4
      .span4
        %h2
          %i.icon-bullhorn
          fundiert wissenschaftlich
        %p Die Ernährungsberatung basiert auf aktuellen wissenschaftlichen Erkenntnissen. Sie orientiert sich zudem an den Empfehlungen der Deutschen Gesellschaft für Ernährung.
      / /span4
      .span4
        %h2
          %i.icon-bar-chart
          von Experten
        %p Unsere Experten sind studierte Diplom-Ökotrophologen. Nach ihrem Studium haben sie bereits aktiv als Ernährungsberater gearbeitet, Ernährungs-Kurse gehalten und Abnehm-Willigen geholfen, ihren Weg erfolgreich zu gehen.
      / /span4
  / ################ FEATURES SECTION END ################
  %hr.line/
  / ################ TESTIMONIALS SECTION START ################
  %section#testimonials
    .row.center
      %h2
        Kundenstimmen
        %i.icon-thumbs-up
      .span3.margintop20
        = image_tag "person1.png"              
        %hr/
        %blockquote
          "Ich habe 15 Kilo abgenommen - ohne zu hungern! Dank VitalCoaches halte ich mein Gewicht nun auch."
        %cite
          Birgit
      .span3.margintop20
        = image_tag "person4.png"              
        %hr/
        %blockquote
          "Bisher dachte ich schon einges über Ernährung zu wissen. Aber was ich hier gelernt habe hat mir die Augen geöffnet. Dadurch konnte ich meine Ernährung so umstellen, dass ich wie von alleine 5 Kilo verloren haben."
        %cite
          Christian
      .span3.margintop20
        = image_tag "person5.png"              
        %hr/
        %blockquote
          "Während meiner Schwangerschaft habe ich ordentlich zugelegt. Nun wollte ich ich wieder auf mein bisheriges Gewicht zurück. Mit VitalCoaches habe ich es geschafft! Und so gesund, dass es der ganzen Familie gut tut."
        %cite
          Diana
      .span3.margintop20
        = image_tag "person2.png"
        %hr/
        %blockquote
          "Bei Diäten habe ich bisher zwar auch abgenommen, hatte danach aber immer den blöden JoJo-Effekt. Hier nicht! Es dauerte zwar eine wenig länger bis ich am Ziel war, aber nun halte ich seit langem mein Wunschgewicht. Mit der persönlichen Unterstüzung der Coaches konnte ich meine Ziele erreichen."
        %cite
          Claudia
  / ################ TESTIMONIALS  SECTION END ################
  %hr.line/
  / ################ SUPPORT SECTION START ################
  %section#support
    .row.center
      %h2 Wir unterstützen Deinen Weg zum Wunschgewicht.
      %p
        Nutze unsere
        %strong unterstützenden Hilfsmittel
        und
        %strong persönlichen Kontakt zu Experten
        um Deine Ziele zu erreichen.
      %br/
      .span4.margintop20
        .row.left
          .span1
            %i.icon-facetime-video.support-icon
          .span3
            %h3 Coaching-Videos
            %ul.unstyled
              %li
                %i.icon-ok
                voller Zugang zu allen Videos
              %li
                %i.icon-ok
                jederzeit und überall anschauen
              %li
                %i.icon-ok
                für PC, Tablet und Smartphone
      .span4.margintop20
        .row.left
          .span1
            %i.icon-phone.support-icon
          .span3
            %h3 Live-Coaching
            %ul.unstyled
              %li
                %i.icon-ok
                per Telefon
              %li
                %i.icon-ok
                immer für Dich erreichbar
              %li
                %i.icon-ok
                frage uns alles!
      .span4.margintop20
        .row.left
          .span1
            %i.icon-group.support-icon
          .span3
            %h3 Community
            %ul.unstyled
              %li
                %i.icon-ok
                Treffe Gleichgesinnte
              %li
                %i.icon-ok
                Quatschen, Spaß haben
              %li
                %i.icon-ok
                Sport-Treffen organisieren
      .span4.margintop40
        .row.left
          .span1
            %i.icon-comments.support-icon
          .span3
            %h3 Chat
            %ul.unstyled
              %li
                %i.icon-ok
                frage Deinen Coach
              %li
                %i.icon-ok
                täglich im Live-Chat
              %li
                %i.icon-ok
                fundierte Antworten auf alle Fragen
      .span4.margintop40
        .row.left
          .span1
            %i.icon-book.support-icon
          .span3
            %h3 
              = link_to "Ernährungstagebuch", diary_path
            %ul.unstyled
              %li
                %i.icon-ok
                führe Buch
              %li
                %i.icon-ok
                einfach Mahlzeiten eintragen
              %li
                %i.icon-ok
                den Kalorien-Überblick behalten
      .span4.margintop40
        .row.left
          .span1
            %i.icon-file.support-icon
          .span3
            %h3 Rezepte
            %ul.unstyled
              %li
                %i.icon-ok
                einfach nachkochen
              %li
                %i.icon-ok
                auf Deine Vorlieben angepasst
              %li
                %i.icon-ok
                lecker für die ganze Familie
  / ################ SUPPORT SECTION START ################
  %hr.line/
  / ################ SIGNUP SECTION START ################
  %section#signup
    .row.center
      .span12
        %h2
          Bereit loszulegen?
          %i.icon-hand-right
        %p
          Lerne jetzt Dein Wunschgewicht zu erreichen!
        = link_to "STARTE JETZT", new_user_registration_path, :class => "btn btn-landing btn-large", :id => "more_infos_button_bottom"        
  / ################ SIGNUP SECTION END ################
  / ################ BOTTOM SECTION START ################
  %section#bottom    
    %hr.line/
    %h2.icon-phone.center 
      %a{:href => "tel:+4972118036869"}
        +49 721 18036869
  / ################ BOTTOM SECTION END ################
  %section#hints
    .row.center
      .span12
        %p
          Image courtesy of photosthock / stockimages / David Castillo Dominici / FreeDigitalPhotos.net
- content_for :inline_scripts do
  = render "page/video_startpage"